trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  solution: 'Personal Portfolio Website.sln'
  projectPath: 'Personal-Portfolio-Website\Personal Portfolio Website.csproj'
  outputPath: '$(Build.ArtifactStagingDirectory)\AppOutput'
  copyToPath: 'C:\agent\portfolio'

stages:
- stage: Build
  jobs:
  - job: BuildDesktopApp
    displayName: 'Build .NET Portfolio Website'
    steps:

    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '6.0'

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        projects: '$(projectPath)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish .NET Project'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(projectPath)'
        arguments: '--configuration $(buildConfiguration) --output $(outputPath)'
        zipAfterPublish: false

    - task: CopyFiles@2
      displayName: 'Copy to Final Target Directory'
      inputs:
        SourceFolder: '$(outputPath)'
        Contents: '**'
        TargetFolder: '$(copyToPath)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: '$(outputPath)'
        ArtifactName: 'drop'
