trigger:
- main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  solution: 'Personal Portfolio Website.sln'
  projectPath: 'Personal-Portfolio-Website/Personal Portfolio Website.csproj'
  outputPath: '$(Build.ArtifactStagingDirectory)/AppOutput'
  copyToPath: 'C:\agent\portfolio'

stages:
- stage: Build
  jobs:
  - job: BuildDesktopApp
    displayName: 'Build .NET Desktop App'
    steps:

    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'

    - task: NuGetCommand@2
      displayName: 'Restore NuGet Packages'
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      displayName: 'Build Solution'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:Configuration=$(buildConfiguration)'
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'

  - script: |
      echo "Build Output Directory Structure:"
      dir "$(Build.SourcesDirectory)" /s /b
    displayName: '🛠️ Debug: Show All Files After Build'


    - task: CopyFiles@2
      displayName: 'Copy Build Output to Staging Directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\s\bin\$(buildConfiguration)'
        Contents: '**\*'
        TargetFolder: '$(outputPath)'

    - task: CopyFiles@2
      displayName: 'Copy to Final Target Directory'
      inputs:
        SourceFolder: '$(outputPath)'
        Contents: '**\*'
        TargetFolder: '$(copyToPath)'

    # - task: CopyFiles@2
    #   displayName: 'Copy to IIS Web Server'
    #   inputs:
    #     SourceFolder: '$(outputPath)'
    #     Contents: '**\*'
    #     TargetFolder: 'C:\inetpub\wwwroot\GoMartDesktopApp'


    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: '$(outputPath)'
        ArtifactName: 'drop'
